@startuml Connection Activity Diagram
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/cerulean-outline/puml-theme-cerulean-outline.puml
skinparam ConditionEndStyle hline
skinparam BackgroundColor white
title Activity Diagram - Connection Component

start
partition Initializing { 
   :Get ConnectorDescriptor PropertyMap;
   :Parse PropertyMap values to variables;
   :Set RedisRepository;
   if(RepositoryIsNull) is (true) then
   :Create new instance;
   else(false)
   endif
   #LightGreen:Return instance;
}
stop
@enduml