@startuml Create Activity Diagram
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/cerulean-outline/puml-theme-cerulean-outline.puml
skinparam ConditionEndStyle hline
skinparam BackgroundColor white
title Activity Diagram - Create Operation
start
partition "Initialization" {
   :Retrieve Connection Info;
   :Retrieve Jedis from Connection;
}
partition "Null Checks" {
   :Retrieve Dynamic Properties;
   if(Required Props Null) is (true) then
   #Pink:**Error**;
   detach
   else(false)
   :Log Values;
   endif
}

partition "Running"{
   if(isHash) is (true) then
   :HSET;
   else (false)
   if(isExpiry) is (true) then
   :SETEX;
   else(false)
   :SET;
   endif
   endif
   if(Global Expiry?) is (true) then
   :EXPIRE;
   else(false)
   endif
   :Return Result;
}

stop
@enduml